### Find all Content
GET http://localhost:8080/api/content

### Find Content by ID
GET http://localhost:8080/api/content


### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My second Blog Post",
  "desc": "My second blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-09-16T14:34:09.6789264",
  "dateUpdated": null,
  "url": ""
}

### Create new  bad Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "",
  "desc": "My second blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-09-16T14:34:09.6789264",
  "dateUpdated": null,
  "url": ""
}


### Update existing Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "MY FIRST BLOG POST",
  "desc": "MY FIRST BLOG POST",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-09-16T14:34:09.6789264",
  "dateUpdated": "2023-09-16T14:34:09.6789264",
  "url": "http://localhost:8080/my-first-blog-post"
}

### Delete by id
DELETE http://localhost:8080/api/content/2











